<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'yii\\gii\\' => array($vendorDir . '/yiisoft/yii2-gii'),
    'yii\\faker\\' => array($vendorDir . '/yiisoft/yii2-faker'),
    'yii\\debug\\' => array($vendorDir . '/yiisoft/yii2-debug'),
    'yii\\composer\\' => array($vendorDir . '/yiisoft/yii2-composer'),
    'yii\\codeception\\' => array($vendorDir . '/yiisoft/yii2-codeception'),
    'yii\\bootstrap\\' => array($vendorDir . '/yiisoft/yii2-bootstrap'),
    'yii\\' => array($vendorDir . '/yiisoft/yii2'),
    'kop\\y2sp\\' => array($vendorDir . '/kop/yii2-scroll-pager'),
    'kartik\\sortable\\' => array($vendorDir . '/kartik-v/yii2-sortable'),
    'kartik\\select2\\' => array($vendorDir . '/kartik-v/yii2-widget-select2'),
    'kartik\\rating\\' => array($vendorDir . '/kartik-v/yii2-widget-rating'),
    'kartik\\popover\\' => array($vendorDir . '/kartik-v/yii2-popover-x'),
    'kartik\\plugins\\popover\\' => array($vendorDir . '/kartik-v/bootstrap-popover-x'),
    'kartik\\plugins\\fileinput\\' => array($vendorDir . '/kartik-v/bootstrap-fileinput'),
    'kartik\\plugins\\depdrop\\' => array($vendorDir . '/kartik-v/dependent-dropdown'),
    'kartik\\mpdf\\' => array($vendorDir . '/kartik-v/yii2-mpdf'),
    'kartik\\grid\\' => array($vendorDir . '/kartik-v/yii2-grid'),
    'kartik\\form\\' => array($vendorDir . '/kartik-v/yii2-widget-activeform'),
    'kartik\\file\\' => array($vendorDir . '/kartik-v/yii2-widget-fileinput'),
    'kartik\\export\\' => array($vendorDir . '/kartik-v/yii2-export'),
    'kartik\\editable\\' => array($vendorDir . '/kartik-v/yii2-editable'),
    'kartik\\dynagrid\\' => array($vendorDir . '/kartik-v/yii2-dynagrid'),
    'kartik\\dialog\\' => array($vendorDir . '/kartik-v/yii2-dialog'),
    'kartik\\depdrop\\' => array($vendorDir . '/kartik-v/yii2-widget-depdrop'),
    'kartik\\datetime\\' => array($vendorDir . '/kartik-v/yii2-widget-datetimepicker'),
    'kartik\\date\\' => array($vendorDir . '/kartik-v/yii2-widget-datepicker'),
    'kartik\\base\\' => array($vendorDir . '/kartik-v/yii2-krajee-base'),
    'drsdre\\wizardwidget\\' => array($vendorDir . '/drsdre/yii2-wizardwidget'),
    'dosamigos\\multiselect\\' => array($vendorDir . '/2amigos/yii2-multi-select-widget'),
    'cebe\\markdown\\' => array($vendorDir . '/cebe/markdown'),
    'bookin\\aws\\checkbox\\' => array($vendorDir . '/bookin/yii2-awesome-bootstrap-checkbox'),
    'beastbytes\\wizard\\' => array($vendorDir . '/beastbytes/yii2-wizard'),
    'Illuminate\\Support\\' => array($vendorDir . '/illuminate/support'),
    'Illuminate\\Contracts\\' => array($vendorDir . '/illuminate/contracts'),
    'Illuminate\\Config\\' => array($vendorDir . '/illuminate/config'),
    'Gufy\\PdfToHtml\\' => array($vendorDir . '/gufy/pdftohtml-php/src'),
    'Faker\\' => array($vendorDir . '/fzaninotto/faker/src/Faker'),
);
