<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'stringEncode' => array($vendorDir . '/paquettg/string-encode/src'),
    'PHPHtmlParser' => array($vendorDir . '/paquettg/php-html-parser/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Gufy' => array($vendorDir . '/gufy/pdftohtml-php/src'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
);
